theme: jekyll-theme-hacker
title: Ipshita Chatterjee
description: Software Developer | Researcher | Technology Enthusiast | Poet | COE Undergraduate at NSIT University of Delhi
show_downloads: true
google_analytics: UA-91764088-1